<a href="https://colab.research.google.com/github/623021000-1thaksina/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ

## list()
- เก็บอะไรก็ได้
- ลำดับในการเก็บ มีความสำคัญ

In [ ]:
list_a = [1,2,3,4,5,6] #[] square brackets

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = ['ab',2,3.14,list_a]

In [ ]:
list_b 

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list

In [ ]:
list_a[3]

4

In [ ]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b[3][4]

5

In [ ]:
list_a[6] #เรียกตัวที่ไม่ได้อยู่ใน list

IndexError: ignored

In [ ]:
list_a[-1] #index -1 คือตัวสุดท้ายของ list 

6

In [ ]:
list_a[-4]

3

### การสร้าง list()

In [ ]:
list_x1 = [] #แบบที่ 1
list_x2 = list() #แบบที่ 2

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย append()

In [ ]:
list_x1.append(2)

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [ ]:
list_x1[0]

2

In [ ]:
list_x1[-1]

4

In [ ]:
list_x2

[]

In [ ]:
list_x2.append('ha')

In [ ]:
list_x2

['ha', 'ha']

### ลบสมาชิกจาก list

In [ ]:
list_x1.append('ha')

In [ ]:
list_x1

[2, 4, 'ha', 'ha']

In [ ]:
list_x1.pop()

'ha'

In [ ]:
list_x1

[2, 4, 'ha']

In [ ]:
list_x1.pop()
print(list_x1)

[2, 4]


### len() ตรวจสอบจำนวนสมาชิกของ list

In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a)

6

### String is a list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculty of Science'

In [ ]:
st_stat[10]

' '

In [ ]:
len(st_stat)

44

### List Slicing 
การเฉือน list

`List[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]`

`List[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง):step]`

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[2]

3

In [ ]:
list_a[-3:] # : colon

[4, 5, 6]

In [ ]:
list_a[:4]

[1, 2, 3, 4]

In [ ]:
list_a[1:4]

[2, 3, 4]

In [ ]:
list_a[:]

[1, 2, 3, 4, 5, 6]

### step

In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [ ]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### range()

In [ ]:
 range(21)

range(0, 21)

In [ ]:
a = list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
list( range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print อกมาให้สวยงาม)

- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [ ]:
#01:02:03

a= (1*60*60) + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาที ได้ {a} วินาที')

01:02:03 แปลงเป็นวินาที ได้ 3723 วินาที


In [ ]:
q1 = '12:30:15'
q1_sp = q1.split(':')
print(q1_sp)
answer1 = int(q1_sp[0])*3600+int(q1_sp[1])*60 +int(q1_sp[2])
print("ตอบ แปลงเป็นวินาที ได้เท่ากับ ",answer1, "วินาที")

['12', '30', '15']
ตอบ แปลงเป็นวินาที ได้เท่ากับ  45015 วินาที


In [ ]:
q2 = '13:41:07'
q2_sp = q2.split(':')
print(q2_sp)
answer2 = int(q2_sp[0])*3600+int(q2_sp[1])*60 +int(q2_sp[2])
print("ตอบ แปลงเป็นวินาที ได้เท่ากับ ",answer2, "วินาที")

['13', '41', '07']
ตอบ แปลงเป็นวินาที ได้เท่ากับ  49267 วินาที


In [ ]:
q3 = '09:11:50'
q3_sp = q3.split(':')
print(q3_sp)
answer3 = int(q3_sp[0])*3600+int(q3_sp[1])*60 +int(q3_sp[2])
print("ตอบ แปลงเป็นวินาที ได้เท่ากับ ",answer3, "วินาที")

['09', '11', '50']
ตอบ แปลงเป็นวินาที ได้เท่ากับ  33110 วินาที


In [ ]:
q4 = '21:30:15'
q4_sp = q4.split(':')
print(q4_sp)
answer4 = int(q4_sp[0])*3600+int(q4_sp[1])*60 +int(q4_sp[2])
print("ตอบ แปลงเป็นวินาที ได้เท่ากับ ",answer4, "วินาที")

['21', '30', '15']
ตอบ แปลงเป็นวินาที ได้เท่ากับ  77415 วินาที


In [ ]:
q5 = '03:10:15'
q5_sp = q5.split(':')
print(q5_sp)
answer5 = int(q5_sp[0])*3600+int(q5_sp[1])*60 +int(q5_sp[2])
print("ตอบ แปลงเป็นวินาที ได้เท่ากับ ",answer5, "วินาที")

['03', '10', '15']
ตอบ แปลงเป็นวินาที ได้เท่ากับ  11415 วินาที


## สร้าง Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ไม่จำเป็นต้องเป็นตัวเลขลำดับ

In [2]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # { } curly backets

In [4]:
dict_a[1]

'Happy'

In [5]:
dict_a['N']

'New'

In [7]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [8]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [10]:
dict_a[7] = 3.14

In [11]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [12]:
dict_a['N'] = 'NNNNEEEEWWWW'

In [13]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

## Numpy Array
- เก็บได้แต่ตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็น Matrix)

In [14]:
import numpy

###1D array

In [18]:
list_A = [1,2,3,4,5]

In [19]:
arr_a = numpy.array(list_A)

In [16]:
arr_a

array([1, 2, 3, 4, 5])

In [20]:
list_A

[1, 2, 3, 4, 5]

In [21]:
arr_a[0]

1

In [22]:
list_A[0]

1

In [23]:
5*arr_a #Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [24]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [25]:
arr_b = numpy.array([10,20,30,40,50])

In [26]:
print(arr_a)

[1 2 3 4 5]


In [27]:
arr_a+arr_b

array([11, 22, 33, 44, 55])

### 2D array

In [28]:
import numpy as np

In [31]:
arr2_z = np.array([[1,2,3], [4,5,6]])

In [30]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2_z.shape

(2, 3)

### np.zeros()

In [33]:
arr2_3_5_0 = np.zeros((3,5))

In [34]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
arr2_3_5_0[1,2] =  #กำหนดค่า

In [36]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
arr2_3_5_0[1,2] #ชี้

9.0

In [38]:
print(list_A) #เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


## np.ones()

In [39]:
arr2_4_5_1 =np.ones((4,5))

In [40]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
arr2_4_5_200 = 200*np.ones((4,5))

In [42]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix operations

####การบวก ลบ matrix 

In [43]:
arr2_4_5_200 + arr2_3_5_0 #การบวก ลบ  matrix shape ต้องเท่ากัน

ValueError: ignored

In [45]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

#### การคูณ matrix

- $a$M scalar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix)
-$M  Matrix คูณ Matrix (แถวคูณหลัก)

aM

In [46]:
5* arr_a #Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [47]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6,],[7,9]])

In [48]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [49]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [50]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

axc, bxc, 

In [51]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [52]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

cxa,cxb

In [55]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [56]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [58]:
mat_a * mat_b #คูณตัวตำแหน่งเดียวกัน

array([[  2,   6,  25],
       [  8,  24, -49]])

####Matrix Slicing

In [63]:
mat_X[:2, :2]

NameError: ignored

HW3

1. สร้าง array ที่เป็นรูป ต้น Christmas
2. slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว

In [64]:
HW3 = np.zeros((10,10))
HW3 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
HW3[::4,2] =1
HW3[::4,4] =1
HW3[::4,ุุุ6] =1
HW3[::4,8] =1

SyntaxError: ignored

## Pandas Dataform (แยกออกไปเป็น Notebook เฉพาะ)